volumes:
  db-data:

networks:
  instavote:
    driver: bridge
    
services:
  vote:
    image: nmendozac/vote:latest
    ports:
      - 6000:80
    depends_on:
      - redis
    networks:
      - instavote

  redis:
    image: redis:alpine
    networks:
      - instavote
  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - instavote
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  
  result:
    image: nmendozac/result:latest
    ports:
      - 6001:4000
    depends_on:
      - db
    networks:
      - instavote

  worker:
    image: nmendozac/worker:latest
    depends_on:
       - redis
       - db
    networks:
       - instavote

