pipeline {
    agent any

    tools {
	  maven 'Maven 3.8.6'
	}
    stages {
        stage('build') {
            when{
                changeset "**/worker/**"
            }
            steps {
                echo 'Compile worker Java App'
				dir('worker'){
				   sh 'mvn compile'
				}                
            }
        }
        stage('test') {
             when{
                changeset "**/worker/**"
            }
            steps {
                echo 'Running Unit Test for worker Java App'
                dir('worker'){
                  sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            when{
                branch 'master'
                changeset "**/worker/**"
            }
             steps {
                echo 'Packaging worker Java App'
                dir('worker'){
                  sh 'mvn package -Dskiptests'
                  archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                 }
            }
        }
        
    }
    post{
            always{
                echo 'Build pipeline is completed... :) '
            }
        }
}
