pipeline {
    agent any

    tools {
	  maven 'Maven 3.8.6'
	}
    stages {
        stage('build') {
            steps {
                echo 'Compile worker Java App'
				dir('worker'){
				   sh 'mvn compile'
				}                
            }
        }
        stage('test') {
            steps {
                echo 'Running Unit Test for worker Java App'
                dir('worker'){
                  sh 'mvn clean test'
                }
            }
        }
        stage('package') {
            steps {
                echo 'Packaging worker Java App'
                dir('worker'){
                  sh 'mvn package -Dskiptests'
                }
            }
        }
        
    }
    post{
            always{
                archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true
                echo 'Build pipeline is completed...'
            }
        }
}
